name: reviewdog
on: [pull_request]
env:
  NODE_VERSION: 18.13.0
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
