name: reviewdog
on:
  pull_request:
  merge_group:
env:
  NODE_VERSION: 18.13.0
jobs:
  lint:
    name: runner / eslint & ts check
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn
      - uses: reviewdog/action-setup@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
      - name: tsc check app
        run: yarn tsc --noEmit | reviewdog -f=tsc -name="typescript check" -reporter=github-pr-check -filter-mode=nofilter -fail-on-error=false -level=error
