name: specs

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 16.10.0

jobs:
  specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: BuoySoftware/github-actions/setup-node@main
        with:
          install-dependencies: false
          node-version: ${{ env.NODE_VERSION }}

      - name: Yarn install
        run: yarn install

      - name: Compile Typescript
        run: yarn compile

      - name: Run specs
        run: yarn test
